"""Add non-nullable restrictions

Revision ID: 2983c9a51184
Revises: 0d7ad8ba3f70
Create Date: 2024-05-08 17:21:36.977757

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2983c9a51184"
down_revision = "0d7ad8ba3f70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("contacts", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contacts", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("companies", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
